import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
  versionAttribute
} from '@aws/dynamodb-data-mapper-annotations';
// import {EntitySchema} from '@breeze-bb/core';

@table('Users')
export class User {
  @autoGeneratedHashKey()
  public id: string;

  @rangeKey({
    defaultProvider: (): Date => new Date()
  })
  public createdAt: Date;

  @versionAttribute()
  public version: number;

  @attribute()
  public emailAddress: string;

  @attribute()
  public firstName: string;

  @attribute()
  public surname: string;
}
