/**
 * @author Mo Gusbi <me@mogusbi.co.uk>
 */
import {attribute, autoGeneratedHashKey, rangeKey} from '@aws/dynamodb-data-mapper-annotations';

/**
 * Base entity class that should be inherited by other entities
 */
export abstract class Base {
  @autoGeneratedHashKey()
  public id: string;

  @rangeKey({
    defaultProvider (): string {
      const date: Date = new Date();

      return date.toISOString();
    }
  })
  public createdAt: string;

  @attribute({
    defaultProvider (): string {
      const date: Date = new Date();

      return date.toISOString();
    }
  })
  public updatedAt: string;
}
