import {autoGeneratedHashKey, rangeKey, versionAttribute} from '@aws/dynamodb-data-mapper-annotations';

export class EntitySchema {
  @autoGeneratedHashKey()
  public id: string;

  @rangeKey({
    defaultProvider: (): Date => new Date()
  })
  public createdAt: Date;

  @versionAttribute()
  public version: number;
}
