"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
var dynamodb_data_mapper_annotations_1 = require("@aws/dynamodb-data-mapper-annotations");
var EntitySchema = /** @class */ (function () {
    function EntitySchema() {
    }
    __decorate([
        dynamodb_data_mapper_annotations_1.autoGeneratedHashKey(),
        __metadata("design:type", String)
    ], EntitySchema.prototype, "id", void 0);
    __decorate([
        dynamodb_data_mapper_annotations_1.rangeKey(),
        __metadata("design:type", Date)
    ], EntitySchema.prototype, "createdAt", void 0);
    __decorate([
        dynamodb_data_mapper_annotations_1.versionAttribute(),
        __metadata("design:type", Number)
    ], EntitySchema.prototype, "version", void 0);
    return EntitySchema;
}());
exports.EntitySchema = EntitySchema;
//# sourceMappingURL=entity.schema.js.map